spring:
    application:
        name: facturation
    datasource:
        url: jdbc:postgresql://localhost:5432/facturation_backend
        username: postgres
        password: postgres
        driverClassName: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                show-sql: true
                dialect: org.hibernate.dialect.PostgreSQLDialect
    
server:
    port: 8100
